<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$P$ChBMZGutGEnq1WAnZiSTMtWU/GFAJx1',
        'loginSecurityLevel' => 'rsa',
        'versionNumberInFilename' => '0',
        'warning_email_addr' => 'media@netlogix.de',
    ],
    'DB' => [
        'database' => '',
        'host' => '',
        'password' => '',
        'port' => 3306,
        'username' => '',
    ],
    'EXT' => [
        'extConf' => [
            'coreapi' => 'a:0:{}',
            'filemetadata' => 'a:0:{}',
            'fluid_styled_content' => 'a:1:{s:32:"loadContentElementWizardTsConfig";s:1:"1";}',
            'gridelements' => 'a:2:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";}',
            'nxt3dd16' => 'a:0:{}',
            'realurl' => 'a:5:{s:10:"configFile";s:34:"typo3conf/RealurlConfiguration.php";s:14:"enableAutoConf";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";s:14:"autoConfFormat";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\PhpassSalt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'sso' => 'a:1:{s:7:"server.";a:1:{s:12:"rsaPublicKey";s:0:"";}}',
            't3dd16' => 'a:0:{}',
        ],
    ],
    'FE' => [
        'debug' => false,
        'loginSecurityLevel' => 'rsa',
    ],
    'GFX' => [
        'colorspace' => 'sRGB',
        'gdlib_png' => 1,
        'im' => 1,
        'im_mask_temp_ext_gif' => 1,
        'im_path' => '/usr/bin/',
        'im_path_lzw' => '/usr/bin/',
        'im_v5effects' => 1,
        'im_version_5' => 'im6',
        'image_processing' => 1,
        'jpg_quality' => '80',
        'thumbnails_png' => 1,
    ],
    'SYS' => [
        'UTF8filesystem' => 1,
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\ApcBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'clearCacheSystem' => false,
        'cookieHttpOnly' => false,
        'devIPmask' => '',
        'disableNoCacheParameter' => true,
        'displayErrors' => 0,
        'doNotCheckReferer' => true,
        'enableDeprecationLog' => false,
        'encryptionKey' => '41ec201f8042c569b0996f4d972b0ada051c2ae17ac541cd5d911a19eeab66ce0e8310c2fdca642426709ce54bf1a53d',
        'exceptionalErrors' => 4341,
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => true,
        'sitename' => 'T3DD16',
        'sqlDebug' => 0,
        'systemLocale' => 'de_DE.UTF-8',
        'systemLog' => 'syslog,LOCAL0',
        'systemLogLevel' => 2,
        't3lib_cs_convMethod' => 'mbstring',
        't3lib_cs_utils' => 'mbstring',
    ],
];
